#ifndef BOIDS_H
# define BOIDS_H

# define MAX_DISTANCE 1500.0f

// SPEED
# define BOID_START_VEL 8.0f
# define BOID_MIN_VEL (0.25f * BOID_START_VEL)
# define BOID_MAX_VEL (2.5f * BOID_START_VEL)

// SEPARATION
# define BOID_SEPARATION_RADIUS 5.0f
# define BOID_SEPARATION_FORCE (3.0f * BOID_START_VEL)

// ALIGNEMENT
# define BOID_ALIGNMENT_RADIUS 10.0f
# define BOID_ALIGNMENT_FORCE (0.5f * BOID_START_VEL)

// COHESION
# define BOID_COHESION_RADIUS 10.0f
# define BOID_COHESION_FORCE (0.2f * BOID_START_VEL)

// BORDER
# define BOID_AVOID_BORDER_FORCE 0.1f

#endif
